library(shiny)
shinyUI(pageWithSidebar(
  headerPanel("THE 5-MINUTE PERSONALITY TEST"),
  sidebarPanel(
    p(paste("For each question, check one that best describe you, then press Submit. We will reveal your personality.",
            "Please answer at least 5 questions. For best result, please answer all 10 questions.")),
    radioButtons(inputId="q1", label="Question 1:", 
                 choices=list("Likes Authority" = "A",
                           "Enthusiastic" = "B",
                           "Sensitive Feelings" = "C",
                           "Likes Instructions" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q2", label="Question 2:", 
                 choices=list("Take Charge" = "A",
                           "Take Risks" = "B",
                           "Loyal" = "C",
                           "Accurate" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q3", label="Question 3:", 
                 choices=list("Determined" = "A",
                           "Visionary" = "B",
                           "Calm" = "C",
                           "Consistent" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q4", label="Question 4:", 
                 choices=list("Enterprising" = "A",
                           "Very Verbal" = "B",
                           "Enjoy Routine" = "C",
                           "Predictable" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q5", label="Question 5:", 
                 choices=list("Competitive" = "A",
                           "Promoter" = "B",
                           "Dislike Change" = "C",
                           "Practical" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q6", label="Question 6:", 
                 choices=list("Problem Solver" = "A",
                           "Enjoy Popularity" = "B",
                           "Gives In To Others" = "C",
                           "Factual" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q7", label="Question 7:", 
                 choices=list("Productive" = "A",
                           "Fun-Loving" = "B",
                           "Avoid Confrontations" = "C",
                           "Conscientious" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q8", label="Question 8:", 
                 choices=list("Bold" = "A",
                           "Like Variety" = "B",
                           "Sympathetic" = "C",
                           "Perfectionist" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q9", label="Question 9:", 
                 choices=list("Decision Maker" = "A",
                           "Spontaneous" = "B",
                           "Nurturing" = "C",
                           "Detail-Oriented" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    radioButtons(inputId="q10", label="Question 10:", 
                 choices=list("Persistent" = "A",
                           "Inspirational" = "B",
                           "Peacemaker" = "C",
                           "Analytical" = "D",
                           "Don't Know or Not Sure" = "E"), selected = "E"),
    p("Please press Submit and roll up to the top right of this page to see your result."),
    submitButton(text="Submit")
  ),
  mainPanel(
    h3("Your Result: "),
    verbatimTextOutput("oAns")
  )
))